// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEFhc2cehHPxd1E3VLnj4_nX_fZ6WwyfI',
    appId: '1:730679614407:web:99a69f4743fcff110b17e2',
    messagingSenderId: '730679614407',
    projectId: 'simple-e-commerce-app-1a222',
    authDomain: 'simple-e-commerce-app-1a222.firebaseapp.com',
    storageBucket: 'simple-e-commerce-app-1a222.firebasestorage.app',
    measurementId: 'G-K4QZBT5QXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4o-l3W950ek6kkpS05Z9mlnY1JVG2K_8',
    appId: '1:730679614407:android:2bd47addbae90d840b17e2',
    messagingSenderId: '730679614407',
    projectId: 'simple-e-commerce-app-1a222',
    storageBucket: 'simple-e-commerce-app-1a222.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHomHoDNt9AbAHNsTNgMOvunhA8FKT3kg',
    appId: '1:730679614407:ios:4c9494573acf222a0b17e2',
    messagingSenderId: '730679614407',
    projectId: 'simple-e-commerce-app-1a222',
    storageBucket: 'simple-e-commerce-app-1a222.firebasestorage.app',
    iosBundleId: 'com.example.simpleECommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHomHoDNt9AbAHNsTNgMOvunhA8FKT3kg',
    appId: '1:730679614407:ios:4c9494573acf222a0b17e2',
    messagingSenderId: '730679614407',
    projectId: 'simple-e-commerce-app-1a222',
    storageBucket: 'simple-e-commerce-app-1a222.firebasestorage.app',
    iosBundleId: 'com.example.simpleECommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEFhc2cehHPxd1E3VLnj4_nX_fZ6WwyfI',
    appId: '1:730679614407:web:8c68377cd2fd0f5e0b17e2',
    messagingSenderId: '730679614407',
    projectId: 'simple-e-commerce-app-1a222',
    authDomain: 'simple-e-commerce-app-1a222.firebaseapp.com',
    storageBucket: 'simple-e-commerce-app-1a222.firebasestorage.app',
    measurementId: 'G-01SXXRKKT5',
  );
}
